create extension if not exists "uuid-ossp";
create table categories(id uuid primary key default uuid_generate_v4(),slug text unique not null,name jsonb not null,sort_order int default 0,created_at timestamptz default now());
create table products(id uuid primary key default uuid_generate_v4(),slug text unique not null,status text default 'draft' check(status in('draft','published','archived')),brand text,category_id uuid references categories(id),content jsonb not null default '{}',specifications jsonb not null default '{}',seo jsonb not null default '{}',images jsonb not null default '[]',pdf_url text,featured boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
create table posts(id uuid primary key default uuid_generate_v4(),slug text unique not null,status text default 'draft',content jsonb not null default '{}',seo jsonb not null default '{}',tags text[] default '{}',published_at timestamptz,created_at timestamptz default now());
create table testimonials(id uuid primary key default uuid_generate_v4(),name text,company text,country text,quote jsonb not null,image_url text,sort_order int default 0,published boolean default false);
create table site_content(id uuid primary key default uuid_generate_v4(),content_key text unique not null,value jsonb not null,updated_at timestamptz default now());
create table leads(id uuid primary key default uuid_generate_v4(),name text not null,email text not null,country text,machine text,message text,source text default 'website',created_at timestamptz default now());
alter table categories enable row level security;alter table products enable row level security;alter table posts enable row level security;alter table testimonials enable row level security;alter table site_content enable row level security;alter table leads enable row level security;
create policy "public published products" on products for select using(status='published');create policy "public published posts" on posts for select using(status='published');create policy "public testimonials" on testimonials for select using(published=true);create policy "public site content" on site_content for select using(true);create policy "authenticated manage products" on products for all to authenticated using(true) with check(true);create policy "authenticated manage posts" on posts for all to authenticated using(true) with check(true);
