'use client';
import {useEffect,useMemo,useState} from 'react';
import Image from 'next/image';
import {Check,ImagePlus,LoaderCircle,LockKeyhole,Plus,Save,Search,Trash2,X} from 'lucide-react';

type Product={id:string;brand:string;name:string;model:string;category:string;subCategory:string;source:'xcmg'|'pdf';image:string;images:string[];description:string;specifications:Record<string,string>;localOnly:true};
type Draft=Omit<Product,'specifications'|'localOnly'> & {specificationsText:string};
const EMPTY:Draft={id:'',brand:'XCMG',name:'',model:'',category:'excavator',subCategory:'crawler-excavator',source:'xcmg',image:'',images:[],description:'',specificationsText:''};
const CATEGORIES=[['excavator','Excavator'],['loader','Loader'],['roller','Roller'],['grader','Motor Grader'],['mixer','Concrete Mixer']];
const api=(password:string,options:RequestInit={})=>fetch('/api/admin/products',{...options,headers:{'Content-Type':'application/json','x-admin-password':password,...options.headers}});
const toDraft=(product:Product):Draft=>({...product,specificationsText:Object.entries(product.specifications||{}).map(([key,value])=>`${key}: ${value}`).join('\n')});
const parseSpecifications=(value:string)=>Object.fromEntries(value.split('\n').map(line=>{const index=line.indexOf(':');return index<0?['','']:[line.slice(0,index).trim(),line.slice(index+1).trim()]}).filter(([key,val])=>key&&val));

export function AdminProductManager(){
  const [password,setPassword]=useState(''),[products,setProducts]=useState<Product[]>([]),[draft,setDraft]=useState<Draft>(EMPTY),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[message,setMessage]=useState(''),[authenticated,setAuthenticated]=useState(false);
  const filtered=useMemo(()=>products.filter(item=>`${item.model} ${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())),[products,query]);
  useEffect(()=>{const saved=sessionStorage.getItem('anlan-admin-password');if(saved){setPassword(saved);void load(saved)}},[]);
  async function load(secret=password){setBusy(true);setMessage('');try{const response=await api(secret);if(!response.ok)throw new Error((await response.json()).error||'Login failed.');setProducts(await response.json());setAuthenticated(true);sessionStorage.setItem('anlan-admin-password',secret);}catch(error){setAuthenticated(false);setMessage(error instanceof Error?error.message:'Login failed.');}finally{setBusy(false)}}
  function newProduct(){setDraft(EMPTY);setMessage('');}
  async function upload(files:FileList|null){if(!files?.length)return;setUploading(true);setMessage('');try{const form=new FormData();[...files].forEach(file=>form.append('images',file));const response=await fetch('/api/admin/upload',{method:'POST',headers:{'x-admin-password':password},body:form}),result=await response.json();if(!response.ok)throw new Error(result.error);setDraft(current=>({...current,images:[...current.images,...result.images],image:current.image||result.images[0]}));setMessage(`${result.images.length} image(s) uploaded.`);}catch(error){setMessage(error instanceof Error?error.message:'Upload failed.');}finally{setUploading(false)}}
  async function save(){setBusy(true);setMessage('');try{const payload={...draft,name:draft.name||`${draft.brand} ${draft.model}`,specifications:parseSpecifications(draft.specificationsText),localOnly:true};const response=await api(password,{method:draft.id?'PUT':'POST',body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error);await load(password);setDraft(toDraft(result.product));setMessage(draft.id?'Product updated successfully.':'Product added successfully.');}catch(error){setMessage(error instanceof Error?error.message:'Save failed.');}finally{setBusy(false)}}
  async function remove(){if(!draft.id||!confirm(`Delete ${draft.model}? This removes the product from the storefront.`))return;setBusy(true);try{const response=await fetch(`/api/admin/products?id=${encodeURIComponent(draft.id)}`,{method:'DELETE',headers:{'x-admin-password':password}}),result=await response.json();if(!response.ok)throw new Error(result.error);setDraft(EMPTY);await load(password);setMessage('Product deleted.');}catch(error){setMessage(error instanceof Error?error.message:'Delete failed.');}finally{setBusy(false)}}
  function removeImage(image:string){setDraft(current=>{const images=current.images.filter(item=>item!==image);return {...current,images,image:current.image===image?(images[0]||''):current.image}})}
  if(!authenticated)return <section className="min-h-screen bg-[#f3f5f2] px-5 pt-36"><div className="mx-auto max-w-md rounded-3xl bg-white p-8 shadow-xl"><div className="grid size-12 place-items-center rounded-2xl bg-lime"><LockKeyhole/></div><h1 className="mt-5 text-3xl font-black">Product Admin</h1><p className="mt-2 text-gray-500">Sign in to manage products and upload local product photos.</p><label className="mt-7 block text-sm font-bold">Admin password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} onKeyDown={event=>event.key==='Enter'&&load()} className="mt-2 w-full rounded-xl border border-black/15 px-4 py-3 outline-none focus:border-black" autoFocus/></label>{message&&<p className="mt-3 text-sm text-red-600">{message}</p>}<button onClick={()=>load()} disabled={busy||!password} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-5 py-3 font-black text-white disabled:opacity-50">{busy?<LoaderCircle className="animate-spin"/>:<LockKeyhole size={18}/>}Sign in</button></div></section>;
  return <section className="min-h-screen bg-[#f3f5f2] pt-28"><div className="mx-auto max-w-[1500px] px-5 pb-16"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Catalog management</p><h1 className="mt-2 text-4xl font-black">Product Admin</h1><p className="mt-2 text-gray-500">{products.length} products · changes appear on the storefront immediately</p></div><button onClick={newProduct} className="inline-flex items-center gap-2 rounded-full bg-lime px-6 py-3 font-black"><Plus size={18}/>Add product</button></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[360px_1fr]"><aside className="rounded-3xl bg-white p-4 shadow-sm"><div className="relative"><Search className="absolute left-3 top-3.5 text-gray-400" size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search model or category" className="w-full rounded-xl border border-black/10 py-3 pl-10 pr-4 outline-none focus:border-black"/></div><div className="mt-3 max-h-[68vh] space-y-2 overflow-y-auto">{filtered.map(product=><button key={product.id} onClick={()=>setDraft(toDraft(product))} className={`flex w-full items-center gap-3 rounded-2xl p-3 text-left ${draft.id===product.id?'bg-lime':'hover:bg-gray-50'}`}><span className="relative size-16 shrink-0 overflow-hidden rounded-xl bg-gray-100"><Image src={product.image} alt="" fill className="object-contain p-1"/></span><span><b className="block">{product.model}</b><small className="capitalize text-gray-500">{product.category} · {product.subCategory.replaceAll('-',' ')}</small></span></button>)}</div></aside>
      <main className="rounded-3xl bg-white p-5 shadow-sm sm:p-8"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black">{draft.id?`Edit ${draft.model}`:'New product'}</h2><p className="mt-1 text-sm text-gray-500">All product images are stored locally on this website.</p></div>{draft.id&&<button onClick={remove} disabled={busy} className="rounded-full p-3 text-red-600 hover:bg-red-50" aria-label="Delete product"><Trash2/></button>}</div>
        <div className="mt-7 grid gap-5 md:grid-cols-2"><Field label="Model *" value={draft.model} onChange={model=>setDraft({...draft,model})}/><Field label="Product name" value={draft.name} onChange={name=>setDraft({...draft,name})} placeholder={`${draft.brand} ${draft.model||'Model'}`}/><Field label="Brand" value={draft.brand} onChange={brand=>setDraft({...draft,brand})}/><label className="text-sm font-bold">Category *<select value={draft.category} onChange={event=>setDraft({...draft,category:event.target.value})} className="mt-2 w-full rounded-xl border border-black/15 bg-white px-4 py-3">{CATEGORIES.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><Field label="Subcategory" value={draft.subCategory} onChange={subCategory=>setDraft({...draft,subCategory})} placeholder="wheel-loader"/><label className="text-sm font-bold md:col-span-2">Description<textarea value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})} rows={4} className="mt-2 w-full rounded-xl border border-black/15 px-4 py-3 outline-none focus:border-black"/></label><label className="text-sm font-bold md:col-span-2">Specifications <span className="font-normal text-gray-400">(one per line: Name: Value)</span><textarea value={draft.specificationsText} onChange={event=>setDraft({...draft,specificationsText:event.target.value})} rows={6} placeholder={'Operating Weight: 21,500 kg\nEngine Power: 129 kW\nBucket Capacity: 1.0 m³'} className="mt-2 w-full rounded-xl border border-black/15 px-4 py-3 font-mono text-sm outline-none focus:border-black"/></label></div>
        <div className="mt-7"><div className="flex items-center justify-between"><h3 className="font-black">Product photos *</h3><label className="inline-flex cursor-pointer items-center gap-2 rounded-full border border-black/15 px-5 py-2.5 font-bold hover:border-black"><ImagePlus size={18}/>{uploading?'Uploading…':'Upload photos'}<input type="file" accept="image/jpeg,image/png,image/webp" multiple className="hidden" disabled={uploading} onChange={event=>upload(event.target.files)}/></label></div><p className="mt-1 text-sm text-gray-500">JPG, PNG or WebP, maximum 12 MB each. Click a photo to make it the cover.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{draft.images.map(image=><div key={image} className={`relative aspect-[4/3] overflow-hidden rounded-2xl bg-gray-100 ring-2 ${draft.image===image?'ring-lime':'ring-transparent'}`}><button onClick={()=>setDraft({...draft,image})} className="absolute inset-0 z-10" aria-label="Set as cover"/><Image src={image} alt="Product" fill className="object-contain p-2"/>{draft.image===image&&<span className="absolute left-2 top-2 z-20 flex items-center gap-1 rounded-full bg-lime px-2 py-1 text-xs font-black"><Check size={12}/>Cover</span>}<button onClick={()=>removeImage(image)} className="absolute right-2 top-2 z-20 rounded-full bg-white p-1.5 shadow" aria-label="Remove image"><X size={14}/></button></div>)}</div></div>
        {message&&<p className={`mt-5 rounded-xl px-4 py-3 text-sm ${/success|uploaded|deleted/i.test(message)?'bg-green-50 text-green-700':'bg-amber-50 text-amber-800'}`}>{message}</p>}<div className="mt-7 flex justify-end"><button onClick={save} disabled={busy||uploading} className="inline-flex items-center gap-2 rounded-full bg-ink px-7 py-3 font-black text-white disabled:opacity-50">{busy?<LoaderCircle className="animate-spin" size={18}/>:<Save size={18}/>}Save product</button></div>
      </main></div></div></section>;
}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="text-sm font-bold">{label}<input value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-black/15 px-4 py-3 outline-none focus:border-black"/></label>}
