import {readFile} from 'fs/promises';import path from 'path';import {readCollection,slugify} from './cms-store';
export type SeoPost={slug:string;title:string;excerpt:string;date:string;category:string;model:string;machineType:string;coverImage?:string;content?:string;seoTitle?:string;seoDescription?:string;sections:{heading:string;body:string}[]};
const categories=['Product Guide','Buying Guide','Import Guide','Maintenance','Factory News','Shipment News','Customer Stories'];
const titleFor=(category:string,model:string)=>({
  'Product Guide':`${model} Specifications, Applications and Price Guide`,
  'Buying Guide':`How to Buy ${model} from China: Buyer Checklist`,
  'Import Guide':`Importing ${model}: Shipping, Documents and Landed Cost`,
  'Maintenance':`${model} Maintenance Checklist for Reliable Operation`,
  'Factory News':`${model} Pre-shipment Inspection and Supply Update`,
  'Shipment News':`${model} Shipping Options: Container, Flat Rack or RoRo`,
  'Customer Stories':`${model} Delivery Case: From China to the Job Site`
}[category]||`${model} Machinery Guide`);
async function generatedPosts():Promise<SeoPost[]>{const products: {model:string;category:string;subCategory:string}[]=JSON.parse(await readFile(path.join(process.cwd(),'data','products.json'),'utf8'));const posts:SeoPost[]=[];products.forEach((product,index)=>{for(let variant=0;variant<3;variant++){const category=categories[(index*3+variant)%categories.length],title=titleFor(category,product.model),machineType=product.subCategory.replaceAll('-',' ');posts.push({slug:slugify(`${category}-${product.model}`),title,excerpt:`Practical export guidance for the ${product.model} ${machineType}, covering selection, inspection, pricing, logistics and after-sales planning.`,date:new Date(Date.UTC(2026,5,21-Math.min(posts.length,20))).toLocaleDateString('en-US',{month:'long',day:'2-digit',year:'numeric',timeZone:'UTC'}),category,model:product.model,machineType,sections:[{heading:`Understanding the ${product.model}`,body:`The ${product.model} is a ${machineType} intended for professional construction and infrastructure work. Match the configuration to material density, duty cycle, climate, attachment requirements and local service capability before comparing quotations.`},{heading:'Verify the machine before payment',body:`Confirm the exact model, serial number, year, configuration and included attachments. Request high-resolution photos, an operating video and a written inspection record. Commercial documents should match the physical machine and agreed Incoterms.`},{heading:'Plan the landed cost',body:`Compare the complete cost to your destination, including machine price, inland transport, export handling, sea freight, insurance, customs charges and local delivery. Container, flat-rack, bulk and RoRo options depend on dimensions, port access and sailing schedules.`},{heading:'Parts and after-sales preparation',body:`Order an initial service kit with filters and common wear parts. Keep the maintenance schedule, parts manual and supplier contact available to the site team so routine service does not interrupt production.`}]});}});return posts;}
export async function getPosts():Promise<SeoPost[]>{const cms=await readCollection<any[]>('blog',[]);const published=cms.filter(post=>post.status!=='Draft').map(post=>({slug:slugify(post.slug||post.title),title:post.title,excerpt:post.seoDescription||post.content?.slice(0,160)||'ANLAN Machinery export update.',date:post.createdDate||post.createdAt||new Date().toLocaleDateString('en-US'),category:'Blog',model:'',machineType:'',coverImage:post.coverImage,content:post.content,seoTitle:post.seoTitle,seoDescription:post.seoDescription,sections:post.content?[{heading:post.title,body:post.content}]:[]}));return published.length?published:generatedPosts();}
export async function getPost(slug:string){return (await getPosts()).find(post=>post.slug===slug);}
